version: "3.9"
services:
  mariadb-primary:
    image: alejandrodu/mariadb-primary

  mariadb-replica-1:
    image: alejandrodu/mariadb-replica
    environment:
      MARIADB_PRIMARY_HOST: mariadb-primary

  mariadb-replica-2:
    image: alejandrodu/mariadb-replica
    environment:
      MARIADB_PRIMARY_HOST: mariadb-primary

  maxscale:
    image: alejandrodu/mariadb-maxscale
    command: --admin_host 0.0.0.0 --admin_secure_gui false
    environment:
      MARIADB_HOST_1: mariadb-primary
      MARIADB_HOST_2: mariadb-replica-1
      MARIADB_HOST_3: mariadb-replica-2
    ports:
      - 4000:4000
      - 8989:8989
      - 27017:27017
